export const SET_BOARD_NUMBERS = 'SET_BOARD_NUMBERS';
export const UPDATE_BOARD_NUMBER = 'UPDATE_BOARD_NUMBER';
export const SET_INITIALIZED = 'SET_INITIALIZED';
export const SET_CORRECT_BUTTON_STATUS = 'SET_CORRECT_BUTTON_STATUS';
export const SET_RANDOM_BUTTON_STATUS = 'SET_RANDOM_BUTTON_STATUS';
export const SWITCH_VIEWS = 'SWITCH_VIEWS';
export const SET_CORRECT_ROW = 'SET_CORRECT_ROW';
